
import java.awt.Color;
import javax.swing.JOptionPane;
import java.sql.Connection;
import java.sql.Statement;
import java.sql.ResultSet;
import java.sql.DriverManager;
import java.sql.SQLException;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author rakesh_pc
 */
public class AddFaculty extends javax.swing.JFrame {

    public AddFaculty() {
        initComponents();
        setExtendedState(JFrame.MAXIMIZED_BOTH); //miximize automatically
        setAllColors();
        setInvisible();
        clear();
        LoadFacultyData();
    }

    /**
     * Creates new form AddFaculty
     */
    Color darkBalck = new Color(0, 0, 0);
    Color headerColor = new Color(44, 45, 45);
    Color menuPanelColor = new Color(60, 60, 60);
    Color tableSelectionColor = new Color(55, 55, 55);

    Color hoverColor = new Color(58, 58, 58);  //rgba(58,58,58,255)
    boolean a = true;
    int mousepX, mousepY;

    public void setInvisible(){
        facId.setVisible(false);
    }
    public void setAllColors() {
        headerPanel.setBackground(headerColor);
        AllIcons.setBackground(menuPanelColor);
        facRecordsTable.setSelectionBackground(tableSelectionColor);

    }

    public void changeImage(JLabel button, String resourcesImg) {
        ImageIcon aimg = new ImageIcon(getClass().getResource(resourcesImg));
        button.setIcon(aimg);

    }

    public void changeColor(JPanel hover, Color rand) {
        hover.setBackground(rand);
    }

    public void clear() {
        fac_txt_search.setText(null);
        facName.setText(null);
        facEmail.setText(null);
        facMobile.setText(null);
        facDetail.setText(null);
        facAddress.setText(null);
        facSeason.setText(null);
        facBtnGroup.clearSelection();
    }

    public void LoadFacultyData() {

        Connection con;
        Statement stmt;
        ResultSet res;
        String qry;
        DefaultTableModel dtm;
        int sno = 1;

        try {
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/db_Book_Record_System", "root", "");
            stmt = con.createStatement();
            qry = "Select * from db_Faculty";
            res = stmt.executeQuery(qry);

            Object[] facRecords = new Object[9];

            dtm = (DefaultTableModel) facRecordsTable.getModel();
            dtm.setRowCount(0);

            while (res.next()) {
                facRecords[0] = sno;
                facRecords[1] = res.getInt("fac_id");
                facRecords[2] = res.getString("fac_name");
                facRecords[3] = res.getString("fac_gender");
                facRecords[4] = res.getString("fac_email");
                facRecords[5] = res.getLong("fac_mobile");
                facRecords[6] = res.getString("fac_detail");
                facRecords[7] = res.getString("fac_address");
                facRecords[8] = res.getString("fac_season");
                dtm.addRow(facRecords);
                sno++;

            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        facBtnGroup = new javax.swing.ButtonGroup();
        addPopUpMenu = new javax.swing.JPopupMenu();
        addStu = new javax.swing.JMenuItem();
        addFac = new javax.swing.JMenuItem();
        addIns = new javax.swing.JMenuItem();
        toolsPopUpMenu = new javax.swing.JPopupMenu();
        cngPass = new javax.swing.JMenuItem();
        cngInsDetails = new javax.swing.JMenuItem();
        bookPopUpMenu = new javax.swing.JPopupMenu();
        manageBook = new javax.swing.JMenuItem();
        issuedBook = new javax.swing.JMenuItem();
        headerPanel = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        close = new javax.swing.JPanel();
        closeIcon = new javax.swing.JLabel();
        minimize = new javax.swing.JPanel();
        minBtn = new javax.swing.JLabel();
        maximize = new javax.swing.JPanel();
        max = new javax.swing.JLabel();
        movePanel = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        Container = new javax.swing.JPanel();
        formPanel = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        JTextField12 = new javax.swing.JLabel();
        facName = new javax.swing.JTextField();
        bName1 = new javax.swing.JLabel();
        facEmail = new javax.swing.JTextField();
        bName2 = new javax.swing.JLabel();
        facMobile = new javax.swing.JTextField();
        bName3 = new javax.swing.JLabel();
        bName4 = new javax.swing.JLabel();
        facAddress = new javax.swing.JTextField();
        AddBtn = new javax.swing.JButton();
        updateBtn = new javax.swing.JButton();
        clearBtn = new javax.swing.JButton();
        delete = new javax.swing.JButton();
        facId = new javax.swing.JTextField();
        bName5 = new javax.swing.JLabel();
        facSeason = new javax.swing.JTextField();
        facDetail = new javax.swing.JTextField();
        bName6 = new javax.swing.JLabel();
        facMale = new javax.swing.JCheckBox();
        facFemale = new javax.swing.JCheckBox();
        facOther = new javax.swing.JCheckBox();
        jLabel1 = new javax.swing.JLabel();
        fac_txt_search = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        dataPanel = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        facRecordsTable = new javax.swing.JTable();
        menuPanel = new javax.swing.JPanel();
        AllIcons = new javax.swing.JPanel();
        homeIconPane = new javax.swing.JPanel();
        homeIcon = new javax.swing.JLabel();
        bookManagePane = new javax.swing.JPanel();
        bookIcon = new javax.swing.JLabel();
        addPane = new javax.swing.JPanel();
        addIcon = new javax.swing.JLabel();
        resetPassPane = new javax.swing.JPanel();
        resetPass = new javax.swing.JLabel();

        addPopUpMenu.setBackground(new java.awt.Color(254, 254, 254));
        addPopUpMenu.setForeground(new java.awt.Color(1, 1, 1));

        addStu.setBackground(new java.awt.Color(254, 254, 254));
        addStu.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        addStu.setForeground(new java.awt.Color(1, 1, 1));
        addStu.setText("add Students");
        addStu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addStuMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                addStuMousePressed(evt);
            }
        });
        addStu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addStuActionPerformed(evt);
            }
        });
        addPopUpMenu.add(addStu);

        addFac.setBackground(new java.awt.Color(254, 238, 238));
        addFac.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        addFac.setForeground(new java.awt.Color(1, 1, 1));
        addFac.setText("add Faculty");
        addFac.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                addFacMousePressed(evt);
            }
        });
        addPopUpMenu.add(addFac);

        addIns.setBackground(new java.awt.Color(254, 254, 254));
        addIns.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        addIns.setForeground(new java.awt.Color(1, 1, 1));
        addIns.setText("add Instructor");
        addIns.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                addInsMousePressed(evt);
            }
        });
        addPopUpMenu.add(addIns);

        toolsPopUpMenu.setBackground(new java.awt.Color(254, 254, 254));
        toolsPopUpMenu.setForeground(new java.awt.Color(1, 1, 1));

        cngPass.setBackground(new java.awt.Color(254, 254, 254));
        cngPass.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        cngPass.setForeground(new java.awt.Color(1, 1, 1));
        cngPass.setText("Change Password");
        cngPass.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cngPassMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                cngPassMousePressed(evt);
            }
        });
        cngPass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cngPassActionPerformed(evt);
            }
        });
        toolsPopUpMenu.add(cngPass);

        cngInsDetails.setBackground(new java.awt.Color(254, 254, 254));
        cngInsDetails.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        cngInsDetails.setForeground(new java.awt.Color(1, 1, 1));
        cngInsDetails.setText("Change Instructor Details");
        cngInsDetails.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cngInsDetailsMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                cngInsDetailsMousePressed(evt);
            }
        });
        cngInsDetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cngInsDetailsActionPerformed(evt);
            }
        });
        toolsPopUpMenu.add(cngInsDetails);

        bookPopUpMenu.setBackground(new java.awt.Color(254, 254, 254));
        bookPopUpMenu.setForeground(new java.awt.Color(1, 1, 1));

        manageBook.setBackground(new java.awt.Color(254, 254, 254));
        manageBook.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        manageBook.setForeground(new java.awt.Color(1, 1, 1));
        manageBook.setText("Manage Books");
        manageBook.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                manageBookMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                manageBookMousePressed(evt);
            }
        });
        manageBook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageBookActionPerformed(evt);
            }
        });
        bookPopUpMenu.add(manageBook);

        issuedBook.setBackground(new java.awt.Color(254, 238, 238));
        issuedBook.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        issuedBook.setForeground(new java.awt.Color(1, 1, 1));
        issuedBook.setText("See Issued Books");
        issuedBook.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                issuedBookMousePressed(evt);
            }
        });
        bookPopUpMenu.add(issuedBook);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true

        );

        headerPanel.setBackground(new java.awt.Color(45, 45, 45));
        headerPanel.setForeground(new java.awt.Color(1, 1, 1));
        headerPanel.setOpaque(false);
        headerPanel.setPreferredSize(new java.awt.Dimension(50, 20));
        headerPanel.setLayout(new java.awt.BorderLayout());

        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        close.setBackground(new java.awt.Color(45, 45, 45));
        close.setPreferredSize(new java.awt.Dimension(50, 50));

        closeIcon.setBackground(new java.awt.Color(97, 89, 224));
        closeIcon.setForeground(new java.awt.Color(97, 89, 224));
        closeIcon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        closeIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/cancel18.png"))); // NOI18N
        closeIcon.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        closeIcon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                closeIconMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                closeIconMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                closeIconMouseExited(evt);
            }
        });

        javax.swing.GroupLayout closeLayout = new javax.swing.GroupLayout(close);
        close.setLayout(closeLayout);
        closeLayout.setHorizontalGroup(
            closeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(closeIcon, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );
        closeLayout.setVerticalGroup(
            closeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, closeLayout.createSequentialGroup()
                .addComponent(closeIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel4.add(close, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 0, 30, 20));

        minimize.setBackground(new java.awt.Color(45, 45, 45));
        minimize.setPreferredSize(new java.awt.Dimension(50, 50));

        minBtn.setBackground(new java.awt.Color(45, 45, 45));
        minBtn.setForeground(new java.awt.Color(97, 89, 224));
        minBtn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        minBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/minus18.png"))); // NOI18N
        minBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                minBtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                minBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                minBtnMouseExited(evt);
            }
        });

        javax.swing.GroupLayout minimizeLayout = new javax.swing.GroupLayout(minimize);
        minimize.setLayout(minimizeLayout);
        minimizeLayout.setHorizontalGroup(
            minimizeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(minBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );
        minimizeLayout.setVerticalGroup(
            minimizeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(minimizeLayout.createSequentialGroup()
                .addComponent(minBtn)
                .addGap(0, 2, Short.MAX_VALUE))
        );

        jPanel4.add(minimize, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 40, 20));

        maximize.setBackground(new java.awt.Color(45, 45, 45));
        maximize.setPreferredSize(new java.awt.Dimension(50, 50));

        max.setBackground(new java.awt.Color(45, 45, 45));
        max.setForeground(new java.awt.Color(97, 89, 224));
        max.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        max.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/maxi18.png"))); // NOI18N
        max.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                maxMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                maxMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                maxMouseExited(evt);
            }
        });

        javax.swing.GroupLayout maximizeLayout = new javax.swing.GroupLayout(maximize);
        maximize.setLayout(maximizeLayout);
        maximizeLayout.setHorizontalGroup(
            maximizeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(max, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );
        maximizeLayout.setVerticalGroup(
            maximizeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(max, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        jPanel4.add(maximize, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 0, 30, 20));

        headerPanel.add(jPanel4, java.awt.BorderLayout.LINE_END);

        movePanel.setBackground(new java.awt.Color(45, 45, 45));
        movePanel.setForeground(new java.awt.Color(255, 0, 0));
        movePanel.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                movePanelMouseDragged(evt);
            }
        });
        movePanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                movePanelMousePressed(evt);
            }
        });

        jLabel5.setBackground(new java.awt.Color(254, 254, 254));
        jLabel5.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(254, 254, 254));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Book Record System");

        javax.swing.GroupLayout movePanelLayout = new javax.swing.GroupLayout(movePanel);
        movePanel.setLayout(movePanelLayout);
        movePanelLayout.setHorizontalGroup(
            movePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1153, Short.MAX_VALUE)
        );
        movePanelLayout.setVerticalGroup(
            movePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, movePanelLayout.createSequentialGroup()
                .addGap(0, 2, Short.MAX_VALUE)
                .addComponent(jLabel5))
        );

        headerPanel.add(movePanel, java.awt.BorderLayout.CENTER);

        getContentPane().add(headerPanel, java.awt.BorderLayout.PAGE_START);

        Container.setLayout(new java.awt.BorderLayout());

        formPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        formPanel.setForeground(new java.awt.Color(254, 254, 254));
        formPanel.setMinimumSize(new java.awt.Dimension(500, 100));
        formPanel.setPreferredSize(new java.awt.Dimension(500, 724));

        jPanel5.setBackground(new java.awt.Color(220, 220, 220));

        JTextField12.setFont(new java.awt.Font("Ubuntu", 0, 14)); // NOI18N
        JTextField12.setForeground(new java.awt.Color(1, 1, 1));
        JTextField12.setText("Faculty Name");

        facName.setBackground(new java.awt.Color(254, 254, 254));
        facName.setForeground(new java.awt.Color(1, 1, 1));

        bName1.setFont(new java.awt.Font("Ubuntu", 0, 14)); // NOI18N
        bName1.setForeground(new java.awt.Color(1, 1, 1));
        bName1.setText("Email");

        facEmail.setBackground(new java.awt.Color(254, 254, 254));
        facEmail.setForeground(new java.awt.Color(1, 1, 1));

        bName2.setFont(new java.awt.Font("Ubuntu", 0, 14)); // NOI18N
        bName2.setForeground(new java.awt.Color(1, 1, 1));
        bName2.setText("Mobile");

        facMobile.setBackground(new java.awt.Color(254, 254, 254));
        facMobile.setForeground(new java.awt.Color(1, 1, 1));

        bName3.setFont(new java.awt.Font("Ubuntu", 0, 14)); // NOI18N
        bName3.setForeground(new java.awt.Color(1, 1, 1));
        bName3.setText("Details");

        bName4.setFont(new java.awt.Font("Ubuntu", 0, 14)); // NOI18N
        bName4.setForeground(new java.awt.Color(1, 1, 1));
        bName4.setText("Address");

        facAddress.setBackground(new java.awt.Color(254, 254, 254));
        facAddress.setForeground(new java.awt.Color(1, 1, 1));

        AddBtn.setBackground(new java.awt.Color(254, 254, 254));
        AddBtn.setFont(new java.awt.Font("Ubuntu", 0, 14)); // NOI18N
        AddBtn.setForeground(new java.awt.Color(1, 1, 1));
        AddBtn.setText("Add");
        AddBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddBtnActionPerformed(evt);
            }
        });

        updateBtn.setBackground(new java.awt.Color(254, 254, 254));
        updateBtn.setFont(new java.awt.Font("Ubuntu", 0, 14)); // NOI18N
        updateBtn.setForeground(new java.awt.Color(1, 1, 1));
        updateBtn.setText("Update");
        updateBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateBtnActionPerformed(evt);
            }
        });

        clearBtn.setBackground(new java.awt.Color(254, 254, 254));
        clearBtn.setFont(new java.awt.Font("Ubuntu", 0, 14)); // NOI18N
        clearBtn.setForeground(new java.awt.Color(1, 1, 1));
        clearBtn.setText("Clear");
        clearBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearBtnActionPerformed(evt);
            }
        });

        delete.setBackground(new java.awt.Color(254, 254, 254));
        delete.setFont(new java.awt.Font("Ubuntu", 0, 14)); // NOI18N
        delete.setForeground(new java.awt.Color(1, 1, 1));
        delete.setText("Delete");
        delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteActionPerformed(evt);
            }
        });

        bName5.setFont(new java.awt.Font("Ubuntu", 0, 14)); // NOI18N
        bName5.setForeground(new java.awt.Color(1, 1, 1));
        bName5.setText("Season");

        facSeason.setBackground(new java.awt.Color(254, 254, 254));
        facSeason.setForeground(new java.awt.Color(1, 1, 1));

        facDetail.setBackground(new java.awt.Color(254, 254, 254));
        facDetail.setForeground(new java.awt.Color(1, 1, 1));

        bName6.setFont(new java.awt.Font("Ubuntu", 0, 14)); // NOI18N
        bName6.setForeground(new java.awt.Color(1, 1, 1));
        bName6.setText("Gender");

        facBtnGroup.add(facMale);
        facMale.setFont(new java.awt.Font("Ubuntu", 0, 14)); // NOI18N
        facMale.setForeground(new java.awt.Color(1, 1, 1));
        facMale.setText("Male");

        facBtnGroup.add(facFemale);
        facFemale.setFont(new java.awt.Font("Ubuntu", 0, 14)); // NOI18N
        facFemale.setForeground(new java.awt.Color(1, 1, 1));
        facFemale.setText("Female");

        facBtnGroup.add(facOther);
        facOther.setFont(new java.awt.Font("Ubuntu", 0, 14)); // NOI18N
        facOther.setForeground(new java.awt.Color(1, 1, 1));
        facOther.setText("Other");

        jLabel1.setBackground(new java.awt.Color(254, 254, 254));
        jLabel1.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(1, 1, 1));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel1.setText("Search Faculty");

        fac_txt_search.setBackground(new java.awt.Color(254, 254, 254));
        fac_txt_search.setForeground(new java.awt.Color(1, 1, 1));
        fac_txt_search.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                fac_txt_searchCaretUpdate(evt);
            }
        });
        fac_txt_search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fac_txt_searchActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(bName5, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(facSeason, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel5Layout.createSequentialGroup()
                            .addComponent(bName4, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(facAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(bName3, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(facDetail, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(jPanel5Layout.createSequentialGroup()
                                    .addComponent(bName2, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(facMobile, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel5Layout.createSequentialGroup()
                                    .addComponent(bName1, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(facEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addComponent(facId, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(AddBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(updateBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(delete, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(clearBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(bName6, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(JTextField12, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(facName, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(facMale)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(facFemale)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(facOther)))))
                .addContainerGap(80, Short.MAX_VALUE))
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fac_txt_search)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fac_txt_search))
                .addGap(31, 31, 31)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JTextField12, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(facName, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bName6, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(facMale)
                    .addComponent(facFemale)
                    .addComponent(facOther))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bName1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(facEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bName2, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(facMobile, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bName3, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(facDetail, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bName4, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(facAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bName5, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(facSeason, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AddBtn)
                    .addComponent(updateBtn)
                    .addComponent(clearBtn)
                    .addComponent(delete))
                .addGap(18, 18, 18)
                .addComponent(facId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(53, Short.MAX_VALUE))
        );

        jLabel3.setBackground(new java.awt.Color(27, 27, 27));
        jLabel3.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(1, 1, 1));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Add Faculty");

        javax.swing.GroupLayout formPanelLayout = new javax.swing.GroupLayout(formPanel);
        formPanel.setLayout(formPanelLayout);
        formPanelLayout.setHorizontalGroup(
            formPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, formPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(formPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        formPanelLayout.setVerticalGroup(
            formPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(formPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        Container.add(formPanel, java.awt.BorderLayout.LINE_START);

        dataPanel.setPreferredSize(new java.awt.Dimension(700, 700));

        jPanel2.setBackground(new java.awt.Color(254, 254, 254));
        jPanel2.setForeground(new java.awt.Color(1, 1, 1));

        jLabel2.setBackground(new java.awt.Color(27, 27, 27));
        jLabel2.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(1, 1, 1));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Faculty Details");

        facRecordsTable.setBackground(new java.awt.Color(254, 254, 254));
        facRecordsTable.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        facRecordsTable.setForeground(new java.awt.Color(1, 1, 1));
        facRecordsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "S.No", "Id", "Faculty Name", "Gender", "Email", "Mobile", "Details", "Address", "Season"
            }
        ));
        facRecordsTable.setRowHeight(25);
        facRecordsTable.setRowMargin(10);
        facRecordsTable.setSelectionBackground(new java.awt.Color(55, 55, 55));
        facRecordsTable.setShowGrid(false);
        facRecordsTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                facRecordsTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(facRecordsTable);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 655, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 551, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout dataPanelLayout = new javax.swing.GroupLayout(dataPanel);
        dataPanel.setLayout(dataPanelLayout);
        dataPanelLayout.setHorizontalGroup(
            dataPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 703, Short.MAX_VALUE)
            .addGroup(dataPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(dataPanelLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        dataPanelLayout.setVerticalGroup(
            dataPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 624, Short.MAX_VALUE)
            .addGroup(dataPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(dataPanelLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        Container.add(dataPanel, java.awt.BorderLayout.CENTER);

        getContentPane().add(Container, java.awt.BorderLayout.CENTER);

        menuPanel.setBackground(new java.awt.Color(60, 61, 60));
        menuPanel.setPreferredSize(new java.awt.Dimension(50, 670));
        menuPanel.setLayout(new java.awt.BorderLayout());

        AllIcons.setBackground(new java.awt.Color(53, 54, 53));
        AllIcons.setPreferredSize(new java.awt.Dimension(50, 1138));

        homeIconPane.setBackground(new java.awt.Color(53, 52, 53));
        homeIconPane.setPreferredSize(new java.awt.Dimension(36, 36));

        homeIcon.setBackground(new java.awt.Color(255, 0, 0));
        homeIcon.setForeground(new java.awt.Color(255, 0, 0));
        homeIcon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        homeIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/HomeIcon.png"))); // NOI18N
        homeIcon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                homeIconMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                homeIconMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                homeIconMouseExited(evt);
            }
        });

        javax.swing.GroupLayout homeIconPaneLayout = new javax.swing.GroupLayout(homeIconPane);
        homeIconPane.setLayout(homeIconPaneLayout);
        homeIconPaneLayout.setHorizontalGroup(
            homeIconPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(homeIconPaneLayout.createSequentialGroup()
                .addComponent(homeIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        homeIconPaneLayout.setVerticalGroup(
            homeIconPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(homeIcon, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        bookManagePane.setBackground(new java.awt.Color(53, 52, 53));
        bookManagePane.setPreferredSize(new java.awt.Dimension(36, 36));

        bookIcon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        bookIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/books.png"))); // NOI18N
        bookIcon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bookIconMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                bookIconMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                bookIconMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                bookIconMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                bookIconMouseReleased(evt);
            }
        });

        javax.swing.GroupLayout bookManagePaneLayout = new javax.swing.GroupLayout(bookManagePane);
        bookManagePane.setLayout(bookManagePaneLayout);
        bookManagePaneLayout.setHorizontalGroup(
            bookManagePaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bookManagePaneLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(bookIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        bookManagePaneLayout.setVerticalGroup(
            bookManagePaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bookIcon, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
        );

        addPane.setBackground(new java.awt.Color(53, 52, 53));
        addPane.setPreferredSize(new java.awt.Dimension(35, 35));

        addIcon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        addIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/add.png"))); // NOI18N
        addIcon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addIconMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                addIconMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                addIconMouseExited(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                addIconMouseReleased(evt);
            }
        });

        javax.swing.GroupLayout addPaneLayout = new javax.swing.GroupLayout(addPane);
        addPane.setLayout(addPaneLayout);
        addPaneLayout.setHorizontalGroup(
            addPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(addIcon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        addPaneLayout.setVerticalGroup(
            addPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(addIcon, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
        );

        resetPassPane.setBackground(new java.awt.Color(53, 52, 53));
        resetPassPane.setPreferredSize(new java.awt.Dimension(36, 36));

        resetPass.setBackground(new java.awt.Color(255, 0, 0));
        resetPass.setForeground(new java.awt.Color(255, 0, 0));
        resetPass.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        resetPass.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/setting.png"))); // NOI18N
        resetPass.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                resetPassMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                resetPassMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                resetPassMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                resetPassMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                resetPassMouseReleased(evt);
            }
        });

        javax.swing.GroupLayout resetPassPaneLayout = new javax.swing.GroupLayout(resetPassPane);
        resetPassPane.setLayout(resetPassPaneLayout);
        resetPassPaneLayout.setHorizontalGroup(
            resetPassPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(resetPassPaneLayout.createSequentialGroup()
                .addComponent(resetPass, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        resetPassPaneLayout.setVerticalGroup(
            resetPassPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(resetPass, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout AllIconsLayout = new javax.swing.GroupLayout(AllIcons);
        AllIcons.setLayout(AllIconsLayout);
        AllIconsLayout.setHorizontalGroup(
            AllIconsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AllIconsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(AllIconsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(homeIconPane, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(AllIconsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(addPane, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE)
                        .addComponent(bookManagePane, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE))
                    .addComponent(resetPassPane, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        AllIconsLayout.setVerticalGroup(
            AllIconsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AllIconsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(homeIconPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(bookManagePane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(addPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(resetPassPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(415, Short.MAX_VALUE))
        );

        menuPanel.add(AllIcons, java.awt.BorderLayout.LINE_START);

        getContentPane().add(menuPanel, java.awt.BorderLayout.LINE_START);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void closeIconMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeIconMouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_closeIconMouseClicked

    private void closeIconMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeIconMouseEntered
        // TODO add your handling code here:
        changeColor(close, hoverColor);
    }//GEN-LAST:event_closeIconMouseEntered

    private void closeIconMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeIconMouseExited
        // TODO add your handling code here:
        changeColor(close, headerColor);
    }//GEN-LAST:event_closeIconMouseExited

    private void minBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minBtnMouseClicked
        // TODO add your handling code here:
        setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_minBtnMouseClicked

    private void minBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minBtnMouseEntered
        // TODO add your handling code here:
        changeColor(minimize, hoverColor);
    }//GEN-LAST:event_minBtnMouseEntered

    private void minBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minBtnMouseExited
        // TODO add your handling code here:
        changeColor(minimize, headerColor);
    }//GEN-LAST:event_minBtnMouseExited

    private void maxMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_maxMouseClicked
        // TODO add your handling code here:

        if (this.getExtendedState() != JFrame.MAXIMIZED_BOTH) {
            this.setExtendedState(JFrame.MAXIMIZED_BOTH);
        } else {
            this.setExtendedState(JFrame.NORMAL);

        }
    }//GEN-LAST:event_maxMouseClicked

    private void maxMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_maxMouseEntered
        // TODO add your handling code here:
        changeColor(maximize, hoverColor);
    }//GEN-LAST:event_maxMouseEntered

    private void maxMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_maxMouseExited
        // TODO add your handling code here:
        changeColor(maximize, headerColor);
    }//GEN-LAST:event_maxMouseExited

    private void movePanelMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_movePanelMouseDragged
        // TODO add your handling code here:
        int thisX = evt.getXOnScreen();
        int thisY = evt.getYOnScreen();
        this.setLocation(thisX - mousepX, thisY - mousepY);
    }//GEN-LAST:event_movePanelMouseDragged

    private void movePanelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_movePanelMousePressed
        // TODO add your handling code here:
        // get location of Window
        mousepX = evt.getX();
        mousepY = evt.getY();
    }//GEN-LAST:event_movePanelMousePressed

    private void homeIconMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homeIconMouseClicked
        // TODO add your handling code here:
        MainScreen ms = new MainScreen();
        ms.setVisible(true);
        dispose();
    }//GEN-LAST:event_homeIconMouseClicked

    private void homeIconMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homeIconMouseEntered
        // TODO add your handling code here:
        changeColor(homeIconPane, darkBalck);
    }//GEN-LAST:event_homeIconMouseEntered

    private void homeIconMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homeIconMouseExited
        // TODO add your handling code here:
        changeColor(homeIconPane, menuPanelColor);
    }//GEN-LAST:event_homeIconMouseExited

    private void bookIconMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bookIconMouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_bookIconMouseClicked

    private void bookIconMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bookIconMouseEntered
        // TODO add your handling code here:
        changeColor(bookManagePane, darkBalck);
    }//GEN-LAST:event_bookIconMouseEntered

    private void bookIconMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bookIconMouseExited
        // TODO add your handling code here:
        changeColor(bookManagePane, menuPanelColor);
    }//GEN-LAST:event_bookIconMouseExited

    private void addIconMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addIconMouseClicked
        // TODO add your handling code here:
        if (evt.isPopupTrigger()) {
            addPopUpMenu.show(this, evt.getX(), evt.getY());
        }
    }//GEN-LAST:event_addIconMouseClicked

    private void addIconMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addIconMouseEntered
        // TODO add your handling code here:
        changeColor(addPane, darkBalck);
    }//GEN-LAST:event_addIconMouseEntered

    private void addIconMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addIconMouseExited
        // TODO add your handling code here:
        changeColor(addPane, menuPanelColor);
    }//GEN-LAST:event_addIconMouseExited

    private void addIconMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addIconMouseReleased
        // TODO add your handling code here:
        if (evt.getButton() == 1) { // 1-left, 2-middle, 3-right button
            addPopUpMenu.show(evt.getComponent(), evt.getX(), evt.getY());
        }
    }//GEN-LAST:event_addIconMouseReleased

    private void resetPassMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_resetPassMouseClicked
        // TODO add your handling code here:
        ChangePassword cp = new ChangePassword();
        cp.setVisible(true);
        cp.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);

    }//GEN-LAST:event_resetPassMouseClicked

    private void resetPassMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_resetPassMouseEntered
        // TODO add your handling code here:
        changeColor(resetPassPane, darkBalck);
    }//GEN-LAST:event_resetPassMouseEntered

    private void resetPassMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_resetPassMouseExited
        // TODO add your handling code here:
        changeColor(resetPassPane, menuPanelColor);
    }//GEN-LAST:event_resetPassMouseExited

    private void resetPassMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_resetPassMouseReleased
        if (evt.getButton() == 1) { // 1-left, 2-middle, 3-right button
            toolsPopUpMenu.show(evt.getComponent(), evt.getX(), evt.getY());
        }
        // TODO add your handling code here:

    }//GEN-LAST:event_resetPassMouseReleased

    private void fac_txt_searchCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_fac_txt_searchCaretUpdate
        // TODO add your handling code here:
        Connection con;
        Statement stmt;
        ResultSet res;
        String qry;
        DefaultTableModel dtm;
        int sno = 1;

        try {
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/db_Book_Record_System", "root", "");
            stmt = con.createStatement();
            qry = "Select * from db_Faculty where fac_name like '%" + fac_txt_search.getText() + "%'";
            res = stmt.executeQuery(qry);

            Object[] facRecords = new Object[9];

            dtm = (DefaultTableModel) facRecordsTable.getModel();
            dtm.setRowCount(0);

            while (res.next()) {
                facRecords[0] = sno;
                facRecords[1] = res.getInt("fac_id");
                facRecords[2] = res.getString("fac_name");
                facRecords[3] = res.getString("fac_gender");
                facRecords[4] = res.getString("fac_email");
                facRecords[5] = res.getLong("fac_mobile");
                facRecords[6] = res.getString("fac_detail");
                facRecords[7] = res.getString("fac_address");
                facRecords[8] = res.getString("fac_season");
                dtm.addRow(facRecords);
                sno++;
                //                System.out.println(num);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e);
        }
    }//GEN-LAST:event_fac_txt_searchCaretUpdate

    private void fac_txt_searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fac_txt_searchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fac_txt_searchActionPerformed

    private void AddBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddBtnActionPerformed
        // TODO add your handling code here:
        String facName, facGender = "", facEmail, facDetail, facAddress, facSeason;
        long facMobile;
        facName = this.facName.getText();
        if (facMale.isSelected()) {
            facGender = "Male";
        } else if (facFemale.isSelected()) {
            facGender = "Female";
        } else if (facOther.isSelected()) {
            facGender = "Other";
        }
        facEmail = this.facEmail.getText();
        facMobile = Long.parseLong(this.facMobile.getText());
        facDetail = this.facDetail.getText();
        facAddress = this.facAddress.getText();
        facSeason = this.facSeason.getText();

        Connection con;
        Statement stmt;
        String qry;

        try {
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/db_Book_Record_System", "root", "");

            qry = "INSERT INTO db_Faculty(fac_name,fac_gender,fac_email,fac_mobile,fac_detail,fac_address,fac_season) VALUES('" + facName + "', '" + facGender + "', '" + facEmail + "', " + facMobile + ",'" + facDetail + "' , '" + facAddress + "', '" + facSeason + "')";
            stmt = con.createStatement();
            int row = stmt.executeUpdate(qry);
            if (row > 0) {
                JOptionPane.showMessageDialog(this, "Data Added");
                LoadFacultyData();
            } else {
                JOptionPane.showMessageDialog(this, "Sorry data not Added");
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e);
        }
    }//GEN-LAST:event_AddBtnActionPerformed

    private void updateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateBtnActionPerformed
        // TODO add your handling code here:

        String facName, facGender = "", facEmail, facDetail, facAddress, facSeason;
        long facMobile;
        facName = this.facName.getText();
        if (facMale.isSelected()) {
            facGender = "Male";
        } else if (facFemale.isSelected()) {
            facGender = "Female";
        } else if (facOther.isSelected()) {
            facGender = "Other";
        }
        facEmail = this.facEmail.getText();
        facMobile = Long.parseLong(this.facMobile.getText());
        facDetail = this.facDetail.getText();
        facAddress = this.facAddress.getText();
        facSeason = this.facSeason.getText();
        Connection con;
        Statement stmt;
        String qry;

        try {
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/db_Book_Record_System", "root", "");
            stmt = con.createStatement();
            qry = "UPDATE db_Faculty SET fac_name = '" + facName + "', fac_gender='" + facGender + "', fac_email='" + facEmail + "',  fac_mobile=" + facMobile + " , fac_detail='" + facDetail + "', fac_address='" + facAddress + "', fac_season='" + facSeason + "' WHERE fac_id = " + Integer.parseInt(facId.getText());

            int row = stmt.executeUpdate(qry);
            if (row > 0) {
                JOptionPane.showMessageDialog(this, "Update Succssesfully");
                LoadFacultyData();
            } else {
                JOptionPane.showMessageDialog(this, "Sorry not Updated.");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e);
        }
    }//GEN-LAST:event_updateBtnActionPerformed

    private void clearBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearBtnActionPerformed
        // TODO add your handling code here:
        clear();
    }//GEN-LAST:event_clearBtnActionPerformed

    private void deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteActionPerformed
        // TODO add your handling code here:

        Connection con;
        Statement stmt;
        String qry;

        int delete = JOptionPane.showConfirmDialog(this,
                "Do you really want to delete?", "Select an Option...", JOptionPane.YES_NO_CANCEL_OPTION);
        try {
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/db_Book_Record_System", "root", "");
            stmt = con.createStatement();
            if (delete == 0) {
                // 0:yes 1:No 2:cancel
                qry = "Delete From db_Faculty where fac_id=" + Integer.parseInt(facId.getText());
                int row = stmt.executeUpdate(qry);
                if (row > 0) {
                    LoadFacultyData();
                } else {
                    JOptionPane.showMessageDialog(this, "Sorry not Deletedted.");
                }
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e);
        }
    }//GEN-LAST:event_deleteActionPerformed

    private void facRecordsTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_facRecordsTableMouseClicked
        // TODO add your handling code here:
        int row = facRecordsTable.getSelectedRow();
        TableModel tm = facRecordsTable.getModel();

        facId.setText(tm.getValueAt(row, 1).toString());
        facName.setText((String) tm.getValueAt(row, 2));
        if (tm.getValueAt(row, 3).toString().equalsIgnoreCase("male")) {
            facMale.setSelected(true);
        } else if (tm.getValueAt(row, 3).toString().equalsIgnoreCase("female")) {
            facFemale.setSelected(true);
        } else {
            facOther.setSelected(true);
        }
        facEmail.setText(tm.getValueAt(row, 4).toString());
        facMobile.setText(tm.getValueAt(row, 5).toString());
        facDetail.setText(tm.getValueAt(row, 6).toString());
        facAddress.setText(tm.getValueAt(row, 7).toString());
        facSeason.setText(tm.getValueAt(row, 8).toString());

    }//GEN-LAST:event_facRecordsTableMouseClicked

    private void addStuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addStuMouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_addStuMouseClicked

    private void addStuMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addStuMousePressed
        // TODO add your handling code here:

        AddStudent as = new AddStudent();
        as.setVisible(true);
        dispose();
    }//GEN-LAST:event_addStuMousePressed

    private void addStuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addStuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addStuActionPerformed

    private void addFacMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addFacMousePressed
        // TODO add your handling code here:
        AddFaculty af = new AddFaculty();
        af.setVisible(true);
        dispose();
    }//GEN-LAST:event_addFacMousePressed

    private void addInsMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addInsMousePressed
        // TODO add your handling code here:
        AddInstructor ai = new AddInstructor();
        ai.setVisible(true);
        dispose();
    }//GEN-LAST:event_addInsMousePressed

    private void cngPassMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cngPassMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_cngPassMouseClicked

    private void cngPassMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cngPassMousePressed
        // TODO add your handling code here:
        ChangePassword cp = new ChangePassword();
        cp.setVisible(true);
        cp.setLocationRelativeTo(null);
        cp.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }//GEN-LAST:event_cngPassMousePressed

    private void cngPassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cngPassActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cngPassActionPerformed

    private void cngInsDetailsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cngInsDetailsMouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_cngInsDetailsMouseClicked

    private void cngInsDetailsMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cngInsDetailsMousePressed
        // TODO add your handling code here:
        ChangeInsDetails cid = new ChangeInsDetails();
        cid.setVisible(true);
        dispose();
    }//GEN-LAST:event_cngInsDetailsMousePressed

    private void cngInsDetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cngInsDetailsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cngInsDetailsActionPerformed

    private void manageBookMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_manageBookMouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_manageBookMouseClicked

    private void manageBookMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_manageBookMousePressed
        // TODO add your handling code here:
        ManageBooks mb = new ManageBooks();
        mb.setVisible(true);
        dispose();
    }//GEN-LAST:event_manageBookMousePressed

    private void manageBookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageBookActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_manageBookActionPerformed

    private void issuedBookMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_issuedBookMousePressed
        // TODO add your handling code here:
        IssuedBooks ib = new IssuedBooks();
        ib.setVisible(true);
        dispose();

    }//GEN-LAST:event_issuedBookMousePressed

    private void bookIconMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bookIconMousePressed
        // TODO add your handling code here:

    }//GEN-LAST:event_bookIconMousePressed

    private void resetPassMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_resetPassMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_resetPassMousePressed

    private void bookIconMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bookIconMouseReleased
        // TODO add your handling code here:
        if (evt.getButton() == 1) { // 1-left, 2-middle, 3-right button
            bookPopUpMenu.show(evt.getComponent(), evt.getX(), evt.getY());
        }
    }//GEN-LAST:event_bookIconMouseReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddFaculty.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddFaculty.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddFaculty.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddFaculty.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddFaculty().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddBtn;
    private javax.swing.JPanel AllIcons;
    private javax.swing.JPanel Container;
    private javax.swing.JLabel JTextField12;
    private javax.swing.JMenuItem addFac;
    private javax.swing.JLabel addIcon;
    private javax.swing.JMenuItem addIns;
    private javax.swing.JPanel addPane;
    private javax.swing.JPopupMenu addPopUpMenu;
    private javax.swing.JMenuItem addStu;
    private javax.swing.JLabel bName1;
    private javax.swing.JLabel bName2;
    private javax.swing.JLabel bName3;
    private javax.swing.JLabel bName4;
    private javax.swing.JLabel bName5;
    private javax.swing.JLabel bName6;
    private javax.swing.JLabel bookIcon;
    private javax.swing.JPanel bookManagePane;
    private javax.swing.JPopupMenu bookPopUpMenu;
    private javax.swing.JButton clearBtn;
    private javax.swing.JPanel close;
    private javax.swing.JLabel closeIcon;
    private javax.swing.JMenuItem cngInsDetails;
    private javax.swing.JMenuItem cngPass;
    private javax.swing.JPanel dataPanel;
    private javax.swing.JButton delete;
    private javax.swing.JTextField facAddress;
    private javax.swing.ButtonGroup facBtnGroup;
    private javax.swing.JTextField facDetail;
    private javax.swing.JTextField facEmail;
    private javax.swing.JCheckBox facFemale;
    private javax.swing.JTextField facId;
    private javax.swing.JCheckBox facMale;
    private javax.swing.JTextField facMobile;
    private javax.swing.JTextField facName;
    private javax.swing.JCheckBox facOther;
    private javax.swing.JTable facRecordsTable;
    private javax.swing.JTextField facSeason;
    public javax.swing.JTextField fac_txt_search;
    private javax.swing.JPanel formPanel;
    private javax.swing.JPanel headerPanel;
    private javax.swing.JLabel homeIcon;
    private javax.swing.JPanel homeIconPane;
    private javax.swing.JMenuItem issuedBook;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JMenuItem manageBook;
    private javax.swing.JLabel max;
    private javax.swing.JPanel maximize;
    private javax.swing.JPanel menuPanel;
    private javax.swing.JLabel minBtn;
    private javax.swing.JPanel minimize;
    private javax.swing.JPanel movePanel;
    private javax.swing.JLabel resetPass;
    private javax.swing.JPanel resetPassPane;
    private javax.swing.JPopupMenu toolsPopUpMenu;
    private javax.swing.JButton updateBtn;
    // End of variables declaration//GEN-END:variables
}
