
import java.awt.Color;
import javax.swing.JOptionPane;
import java.sql.Connection;
import java.sql.Statement;
import java.sql.ResultSet;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author rakesh_pc
 */
public class ChangePassword extends javax.swing.JFrame {

    /**
     * Creates new form AddFaculty
     */
    Color darkBalck = new Color(0, 0, 0);
    Color headerColor = new Color(44, 45, 45);
    Color menuPanelColor = new Color(60, 60, 60);
    Color hoverColor = new Color(58, 58, 58);  //rgba(58,58,58,255)
    boolean a = true;
    int mousepX, mousepY;

    public void setAllColors() {
        headerPanel.setBackground(headerColor);
//        AllIcons.setBackground(menuPanelColor);
    }

    public void changeImage(JLabel button, String resourcesImg) {
        ImageIcon aimg = new ImageIcon(getClass().getResource(resourcesImg));
        button.setIcon(aimg);

    }

    public void changeColor(JPanel hover, Color rand) {
        hover.setBackground(rand);
    }

    public ChangePassword() {
        initComponents();
//        setExtendedState(JFrame.MAXIMIZED_BOTH); //miximize automatically

//        clear();
//        LoadFacultyData();
    }

    public void clear() {

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        facBtnGroup = new javax.swing.ButtonGroup();
        addPopUpMenu = new javax.swing.JPopupMenu();
        addStu = new javax.swing.JMenuItem();
        addFac = new javax.swing.JMenuItem();
        addIns = new javax.swing.JMenuItem();
        toolsPopUpMenu = new javax.swing.JPopupMenu();
        cngPass = new javax.swing.JMenuItem();
        cngInsDetails = new javax.swing.JMenuItem();
        bookPopUpMenu = new javax.swing.JPopupMenu();
        manageBook = new javax.swing.JMenuItem();
        issuedBook = new javax.swing.JMenuItem();
        headerPanel = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        close = new javax.swing.JPanel();
        closeIcon = new javax.swing.JLabel();
        minimize = new javax.swing.JPanel();
        minBtn = new javax.swing.JLabel();
        maximize = new javax.swing.JPanel();
        max = new javax.swing.JLabel();
        movePanel = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        prePass = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        newPass = new javax.swing.JPasswordField();
        jLabel3 = new javax.swing.JLabel();
        cngPassBtn = new javax.swing.JButton();

        addPopUpMenu.setBackground(new java.awt.Color(254, 254, 254));
        addPopUpMenu.setForeground(new java.awt.Color(1, 1, 1));

        addStu.setBackground(new java.awt.Color(254, 254, 254));
        addStu.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        addStu.setForeground(new java.awt.Color(1, 1, 1));
        addStu.setText("add Students");
        addStu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addStuMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                addStuMousePressed(evt);
            }
        });
        addStu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addStuActionPerformed(evt);
            }
        });
        addPopUpMenu.add(addStu);

        addFac.setBackground(new java.awt.Color(254, 238, 238));
        addFac.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        addFac.setForeground(new java.awt.Color(1, 1, 1));
        addFac.setText("add Faculty");
        addFac.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                addFacMousePressed(evt);
            }
        });
        addPopUpMenu.add(addFac);

        addIns.setBackground(new java.awt.Color(254, 254, 254));
        addIns.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        addIns.setForeground(new java.awt.Color(1, 1, 1));
        addIns.setText("add Instructor");
        addIns.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                addInsMousePressed(evt);
            }
        });
        addPopUpMenu.add(addIns);

        toolsPopUpMenu.setBackground(new java.awt.Color(254, 254, 254));
        toolsPopUpMenu.setForeground(new java.awt.Color(1, 1, 1));

        cngPass.setBackground(new java.awt.Color(254, 254, 254));
        cngPass.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        cngPass.setForeground(new java.awt.Color(1, 1, 1));
        cngPass.setText("Change Password");
        cngPass.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cngPassMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                cngPassMousePressed(evt);
            }
        });
        cngPass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cngPassActionPerformed(evt);
            }
        });
        toolsPopUpMenu.add(cngPass);

        cngInsDetails.setBackground(new java.awt.Color(254, 254, 254));
        cngInsDetails.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        cngInsDetails.setForeground(new java.awt.Color(1, 1, 1));
        cngInsDetails.setText("Change Instructor Details");
        cngInsDetails.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cngInsDetailsMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                cngInsDetailsMousePressed(evt);
            }
        });
        cngInsDetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cngInsDetailsActionPerformed(evt);
            }
        });
        toolsPopUpMenu.add(cngInsDetails);

        bookPopUpMenu.setBackground(new java.awt.Color(254, 254, 254));
        bookPopUpMenu.setForeground(new java.awt.Color(1, 1, 1));

        manageBook.setBackground(new java.awt.Color(254, 254, 254));
        manageBook.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        manageBook.setForeground(new java.awt.Color(1, 1, 1));
        manageBook.setText("Manage Books");
        manageBook.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                manageBookMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                manageBookMousePressed(evt);
            }
        });
        manageBook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageBookActionPerformed(evt);
            }
        });
        bookPopUpMenu.add(manageBook);

        issuedBook.setBackground(new java.awt.Color(254, 238, 238));
        issuedBook.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        issuedBook.setForeground(new java.awt.Color(1, 1, 1));
        issuedBook.setText("See Issued Books");
        issuedBook.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                issuedBookMousePressed(evt);
            }
        });
        bookPopUpMenu.add(issuedBook);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true

        );

        headerPanel.setBackground(new java.awt.Color(45, 45, 45));
        headerPanel.setForeground(new java.awt.Color(1, 1, 1));
        headerPanel.setOpaque(false);
        headerPanel.setPreferredSize(new java.awt.Dimension(50, 20));
        headerPanel.setLayout(new java.awt.BorderLayout());

        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        close.setBackground(new java.awt.Color(45, 45, 45));
        close.setPreferredSize(new java.awt.Dimension(50, 50));

        closeIcon.setBackground(new java.awt.Color(97, 89, 224));
        closeIcon.setForeground(new java.awt.Color(97, 89, 224));
        closeIcon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        closeIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/cancel18.png"))); // NOI18N
        closeIcon.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        closeIcon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                closeIconMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                closeIconMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                closeIconMouseExited(evt);
            }
        });

        javax.swing.GroupLayout closeLayout = new javax.swing.GroupLayout(close);
        close.setLayout(closeLayout);
        closeLayout.setHorizontalGroup(
            closeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(closeLayout.createSequentialGroup()
                .addComponent(closeIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 12, Short.MAX_VALUE))
        );
        closeLayout.setVerticalGroup(
            closeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, closeLayout.createSequentialGroup()
                .addComponent(closeIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel4.add(close, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 0, 30, 20));

        minimize.setBackground(new java.awt.Color(45, 45, 45));
        minimize.setPreferredSize(new java.awt.Dimension(50, 50));

        minBtn.setBackground(new java.awt.Color(45, 45, 45));
        minBtn.setForeground(new java.awt.Color(97, 89, 224));
        minBtn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        minBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/minus18.png"))); // NOI18N
        minBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                minBtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                minBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                minBtnMouseExited(evt);
            }
        });

        javax.swing.GroupLayout minimizeLayout = new javax.swing.GroupLayout(minimize);
        minimize.setLayout(minimizeLayout);
        minimizeLayout.setHorizontalGroup(
            minimizeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(minimizeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(minBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE))
        );
        minimizeLayout.setVerticalGroup(
            minimizeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(minimizeLayout.createSequentialGroup()
                .addComponent(minBtn)
                .addGap(0, 2, Short.MAX_VALUE))
        );

        jPanel4.add(minimize, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 40, 20));

        maximize.setBackground(new java.awt.Color(45, 45, 45));
        maximize.setPreferredSize(new java.awt.Dimension(50, 50));

        max.setBackground(new java.awt.Color(45, 45, 45));
        max.setForeground(new java.awt.Color(97, 89, 224));
        max.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        max.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/maxi18.png"))); // NOI18N
        max.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                maxMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                maxMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                maxMouseExited(evt);
            }
        });

        javax.swing.GroupLayout maximizeLayout = new javax.swing.GroupLayout(maximize);
        maximize.setLayout(maximizeLayout);
        maximizeLayout.setHorizontalGroup(
            maximizeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(max, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );
        maximizeLayout.setVerticalGroup(
            maximizeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(max, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        jPanel4.add(maximize, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 0, 30, 20));

        headerPanel.add(jPanel4, java.awt.BorderLayout.LINE_END);

        movePanel.setBackground(new java.awt.Color(45, 45, 45));
        movePanel.setForeground(new java.awt.Color(255, 0, 0));
        movePanel.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                movePanelMouseDragged(evt);
            }
        });
        movePanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                movePanelMousePressed(evt);
            }
        });

        jLabel5.setBackground(new java.awt.Color(254, 254, 254));
        jLabel5.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(254, 254, 254));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Book Record System");

        javax.swing.GroupLayout movePanelLayout = new javax.swing.GroupLayout(movePanel);
        movePanel.setLayout(movePanelLayout);
        movePanelLayout.setHorizontalGroup(
            movePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
        );
        movePanelLayout.setVerticalGroup(
            movePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, movePanelLayout.createSequentialGroup()
                .addGap(0, 2, Short.MAX_VALUE)
                .addComponent(jLabel5))
        );

        headerPanel.add(movePanel, java.awt.BorderLayout.CENTER);

        getContentPane().add(headerPanel, java.awt.BorderLayout.PAGE_START);

        jLabel1.setText("Previous Password");

        jLabel2.setText("New Password");

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Change Password");

        cngPassBtn.setText("Change");
        cngPassBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cngPassBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 177, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(newPass, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(prePass, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(142, 142, 142)
                .addComponent(cngPassBtn)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(59, 59, 59)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(prePass))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(newPass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(cngPassBtn)
                .addContainerGap(120, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void closeIconMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeIconMouseClicked
        // TODO add your handling code here:
        ChangePassword cp = new ChangePassword();
        setVisible(false);
    }//GEN-LAST:event_closeIconMouseClicked

    private void closeIconMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeIconMouseEntered
        // TODO add your handling code here:
        changeColor(close, hoverColor);
    }//GEN-LAST:event_closeIconMouseEntered

    private void closeIconMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeIconMouseExited
        // TODO add your handling code here:
        changeColor(close, headerColor);
    }//GEN-LAST:event_closeIconMouseExited

    private void minBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minBtnMouseClicked
        // TODO add your handling code here:
        setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_minBtnMouseClicked

    private void minBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minBtnMouseEntered
        // TODO add your handling code here:
        changeColor(minimize, hoverColor);
    }//GEN-LAST:event_minBtnMouseEntered

    private void minBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minBtnMouseExited
        // TODO add your handling code here:
        changeColor(minimize, headerColor);
    }//GEN-LAST:event_minBtnMouseExited

    private void maxMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_maxMouseClicked
        // TODO add your handling code here:

        if (this.getExtendedState() != JFrame.MAXIMIZED_BOTH) {
            this.setExtendedState(JFrame.MAXIMIZED_BOTH);
        } else {
            this.setExtendedState(JFrame.NORMAL);

        }
    }//GEN-LAST:event_maxMouseClicked

    private void maxMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_maxMouseEntered
        // TODO add your handling code here:
        changeColor(maximize, hoverColor);
    }//GEN-LAST:event_maxMouseEntered

    private void maxMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_maxMouseExited
        // TODO add your handling code here:
        changeColor(maximize, headerColor);
    }//GEN-LAST:event_maxMouseExited

    private void movePanelMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_movePanelMouseDragged
        // TODO add your handling code here:
        int thisX = evt.getXOnScreen();
        int thisY = evt.getYOnScreen();
        this.setLocation(thisX - mousepX, thisY - mousepY);
    }//GEN-LAST:event_movePanelMouseDragged

    private void movePanelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_movePanelMousePressed
        // TODO add your handling code here:
        // get location of Window
        mousepX = evt.getX();
        mousepY = evt.getY();
    }//GEN-LAST:event_movePanelMousePressed

    private void addStuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addStuMouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_addStuMouseClicked

    private void addStuMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addStuMousePressed
        // TODO add your handling code here:

        AddStudent as = new AddStudent();
        as.setVisible(true);
        dispose();
    }//GEN-LAST:event_addStuMousePressed

    private void addStuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addStuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addStuActionPerformed

    private void addFacMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addFacMousePressed
        // TODO add your handling code here:
        AddFaculty af = new AddFaculty();
        af.setVisible(true);
        dispose();
    }//GEN-LAST:event_addFacMousePressed

    private void addInsMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addInsMousePressed
        // TODO add your handling code here:
        AddInstructor ai = new AddInstructor();
        ai.setVisible(true);
        dispose();
    }//GEN-LAST:event_addInsMousePressed

    private void cngPassBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cngPassBtnActionPerformed
        // TODO add your handling code here:
        try {
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/db_Book_Record_System", "root", "");
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery("Select * from db_Instructor");
            
            while (rs.next()) {
                String email = rs.getString("ins_email");
                String prePass = this.prePass.getText();
                String pass = rs.getString("ins_pass");
                String newPass = this.newPass.getText();
                if (prePass.equals(pass)) {

                    Statement st1 = con.createStatement();
                    int row = st1.executeUpdate("UPDATE db_Instructor SET ins_pass='" + newPass + "' where ins_email='" + email + "'");//query i am using to update the password
                    if (row > 0) {
                        JOptionPane.showMessageDialog(null, "PASSWORD UPDATE SUCCESSFUL");
                    } else {
                        JOptionPane.showMessageDialog(null, "PASSWORD UPDATE NOT SUCCESSFUL");

                    }
                } else {
                    JOptionPane.showMessageDialog(this, "USERNAME NOT FOUND");
                }

                
            }

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, e);
        }
    }//GEN-LAST:event_cngPassBtnActionPerformed

    private void cngPassMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cngPassMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_cngPassMouseClicked

    private void cngPassMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cngPassMousePressed
        // TODO add your handling code here:
        ChangePassword cp = new ChangePassword();
        cp.setVisible(true);
        cp.setLocationRelativeTo(null);
        cp.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }//GEN-LAST:event_cngPassMousePressed

    private void cngPassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cngPassActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cngPassActionPerformed

    private void cngInsDetailsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cngInsDetailsMouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_cngInsDetailsMouseClicked

    private void cngInsDetailsMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cngInsDetailsMousePressed
        // TODO add your handling code here:
        ChangeInsDetails cid = new ChangeInsDetails();
        cid.setVisible(true);
        dispose();
    }//GEN-LAST:event_cngInsDetailsMousePressed

    private void cngInsDetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cngInsDetailsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cngInsDetailsActionPerformed

    private void manageBookMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_manageBookMouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_manageBookMouseClicked

    private void manageBookMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_manageBookMousePressed
        // TODO add your handling code here:
        ManageBooks mb = new ManageBooks();
        mb.setVisible(true);
        dispose();
    }//GEN-LAST:event_manageBookMousePressed

    private void manageBookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageBookActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_manageBookActionPerformed

    private void issuedBookMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_issuedBookMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_issuedBookMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddFaculty.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddFaculty.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddFaculty.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddFaculty.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ChangePassword().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem addFac;
    private javax.swing.JMenuItem addIns;
    private javax.swing.JPopupMenu addPopUpMenu;
    private javax.swing.JMenuItem addStu;
    private javax.swing.JPopupMenu bookPopUpMenu;
    private javax.swing.JPanel close;
    private javax.swing.JLabel closeIcon;
    private javax.swing.JMenuItem cngInsDetails;
    private javax.swing.JMenuItem cngPass;
    private javax.swing.JButton cngPassBtn;
    private javax.swing.ButtonGroup facBtnGroup;
    private javax.swing.JPanel headerPanel;
    private javax.swing.JMenuItem issuedBook;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JMenuItem manageBook;
    private javax.swing.JLabel max;
    private javax.swing.JPanel maximize;
    private javax.swing.JLabel minBtn;
    private javax.swing.JPanel minimize;
    private javax.swing.JPanel movePanel;
    private javax.swing.JPasswordField newPass;
    private javax.swing.JPasswordField prePass;
    private javax.swing.JPopupMenu toolsPopUpMenu;
    // End of variables declaration//GEN-END:variables
}
